---
- name: Downloads Hashicorp's otto
  get_url: >
    url="{{ install.download_location }}/{{ otto.version }}_linux_{{ otto.arch }}.zip"
    dest="/tmp/"
    mode=0755
  sudo: yes
  tags:
    - hashicorp
    - otto

- name: Downloads Hashicorp's otto
  unarchive: >
    src="/tmp/{{ otto.version }}_linux_{{ otto.arch }}.zip"
    dest="{{ install.dir }}"
    mode=0755
  sudo: yes
  tags:
    - hashicorp
    - otto
